name: Deploy to S3 (Frontend)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync files to S3
      run: |
        aws s3 sync ./src/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

    - name: Create artifact to S3
      run: |                
        cd build
        zip -r frontend_app.zip .
        
        aws s3 cp frontend_app.zip s3://${{ secrets.S3_BUCKET_NAME }}/frontend/frontend_app.zip
        rm frontend_app.zip
        
        echo "Artifact uploaded to S3 bucket"
