name: Deploy to S3 (Backend)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create artifact to S3
      run: |        
        cd backend
        zip -r backend_app.zip .
        
        aws s3 cp backend_app.zip s3://${{ secrets.S3_BUCKET_NAME }}/backend/backend_app.zip
        rm backend_app.zip
